name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd fastapi-book-project
            git pull origin main
            docker build -t fastapi-app .
            docker stop $(docker ps -q)
            docker run -d -p 8000:8000 fastapi-app
            docker exec trusting_driscoll alembic upgrade head
            sudo systemctl restart nginx
